var annotated_dup =
[
    [ "lrc", "namespacelrc.html", [
      [ "LrcParser", "classlrc_1_1_lrc_parser.html", "classlrc_1_1_lrc_parser" ],
      [ "Lyrics", "classlrc_1_1_lyrics.html", "classlrc_1_1_lyrics" ]
    ] ],
    [ "moodycamel", "namespacemoodycamel.html", [
      [ "spsc_sema", "namespacemoodycamel_1_1spsc__sema.html", [
        [ "LightweightSemaphore", "classmoodycamel_1_1spsc__sema_1_1_lightweight_semaphore.html", "classmoodycamel_1_1spsc__sema_1_1_lightweight_semaphore" ]
      ] ],
      [ "BlockingReaderWriterCircularBuffer", "classmoodycamel_1_1_blocking_reader_writer_circular_buffer.html", "classmoodycamel_1_1_blocking_reader_writer_circular_buffer" ],
      [ "BlockingReaderWriterQueue", "classmoodycamel_1_1_blocking_reader_writer_queue.html", "classmoodycamel_1_1_blocking_reader_writer_queue" ],
      [ "ReaderWriterQueue", "classmoodycamel_1_1_reader_writer_queue.html", "classmoodycamel_1_1_reader_writer_queue" ],
      [ "weak_atomic", "classmoodycamel_1_1weak__atomic.html", "classmoodycamel_1_1weak__atomic" ]
    ] ],
    [ "AudioDataInfo", "struct_audio_data_info.html", "struct_audio_data_info" ],
    [ "AudioFrame", "class_audio_frame.html", "class_audio_frame" ],
    [ "Controller", "class_controller.html", "class_controller" ],
    [ "CountDownLatch", "class_count_down_latch.html", "class_count_down_latch" ],
    [ "CrashReporter", "class_crash_reporter.html", "class_crash_reporter" ],
    [ "CursorPosProvider", "class_cursor_pos_provider.html", "class_cursor_pos_provider" ],
    [ "DecodeDispatcher", "class_decode_dispatcher.html", "class_decode_dispatcher" ],
    [ "DecoderContext", "class_decoder_context.html", "class_decoder_context" ],
    [ "DecoderImpl", "class_decoder_impl.html", "class_decoder_impl" ],
    [ "DecoderImpl< Audio >", "class_decoder_impl_3_01_audio_01_4.html", "class_decoder_impl_3_01_audio_01_4" ],
    [ "DecoderImpl< Video >", "class_decoder_impl_3_01_video_01_4.html", "class_decoder_impl_3_01_video_01_4" ],
    [ "DemuxDispatcherBase", "class_demux_dispatcher_base.html", "class_demux_dispatcher_base" ],
    [ "Demuxer", "class_demuxer.html", "class_demuxer" ],
    [ "Fireworks", "class_fireworks.html", "class_fireworks" ],
    [ "FireworksRenderer", "class_fireworks_renderer.html", "class_fireworks_renderer" ],
    [ "FrameController", "class_frame_controller.html", "class_frame_controller" ],
    [ "HotLoader", "class_hot_loader.html", "class_hot_loader" ],
    [ "HotPlugDetector", "class_hot_plug_detector.html", "class_hot_plug_detector" ],
    [ "Hurricane", "class_hurricane.html", "class_hurricane" ],
    [ "IDemuxDecoder", "class_i_demux_decoder.html", "class_i_demux_decoder" ],
    [ "infoAccessor", "classinfo_accessor.html", "classinfo_accessor" ],
    [ "ListItem", "class_list_item.html", "class_list_item" ],
    [ "Logger", "class_logger.html", "class_logger" ],
    [ "LyricsData", "class_lyrics_data.html", "class_lyrics_data" ],
    [ "LyricSentence", "class_lyric_sentence.html", "class_lyric_sentence" ],
    [ "LyricsReader", "class_lyrics_reader.html", "class_lyrics_reader" ],
    [ "Playback", "class_playback.html", "class_playback" ],
    [ "PlayList", "class_play_list.html", "class_play_list" ],
    [ "PlayListItem", "class_play_list_item.html", "class_play_list_item" ],
    [ "PonyAudioFormat", "class_pony_audio_format.html", "class_pony_audio_format" ],
    [ "PonyAudioSink", "class_pony_audio_sink.html", "class_pony_audio_sink" ],
    [ "PonyKVConnect", "class_pony_k_v_connect.html", "class_pony_k_v_connect" ],
    [ "PonyKVList", "class_pony_k_v_list.html", "class_pony_k_v_list" ],
    [ "PonySampleFormat", "struct_pony_sample_format.html", "struct_pony_sample_format" ],
    [ "Preview", "class_preview.html", "class_preview" ],
    [ "Previewer", "class_previewer.html", "class_previewer" ],
    [ "RenderSettings", "struct_render_settings.html", "struct_render_settings" ],
    [ "ReverseDecodeDispatcher", "class_reverse_decode_dispatcher.html", "class_reverse_decode_dispatcher" ],
    [ "ReverseDecoderImpl", "class_reverse_decoder_impl.html", "class_reverse_decoder_impl" ],
    [ "ReverseDecoderImpl< Audio >", "class_reverse_decoder_impl_3_01_audio_01_4.html", "class_reverse_decoder_impl_3_01_audio_01_4" ],
    [ "ReverseDecoderImpl< Video >", "class_reverse_decoder_impl_3_01_video_01_4.html", "class_reverse_decoder_impl_3_01_video_01_4" ],
    [ "simpleListItem", "classsimple_list_item.html", "classsimple_list_item" ],
    [ "sonicStreamStruct", "structsonic_stream_struct.html", "structsonic_stream_struct" ],
    [ "StreamInfo", "class_stream_info.html", "class_stream_info" ],
    [ "Thumbnail", "class_thumbnail.html", "class_thumbnail" ],
    [ "TwinsBlockQueue", "class_twins_block_queue.html", "class_twins_block_queue" ],
    [ "UpdateValue", "class_update_value.html", "class_update_value" ],
    [ "UpdateValueVideoFrameRef", "class_update_value_video_frame_ref.html", "class_update_value_video_frame_ref" ],
    [ "VideoFrame", "class_video_frame.html", "class_video_frame" ],
    [ "VideoFrameRef", "class_video_frame_ref.html", "class_video_frame_ref" ],
    [ "VirtualVideoDecoder", "class_virtual_video_decoder.html", "class_virtual_video_decoder" ],
    [ "WaveView", "class_wave_view.html", "class_wave_view" ]
];