// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_quickitem();
Q_GHS_KEEP_REFERENCE(qml_register_types_quickitem);

class quickitemPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    quickitemPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_quickitem;
        Q_UNUSED(registration);
    }
};



#include "quickitem_quickitemPlugin.moc"
