add_test( example_test.const_double /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests/unit_tests [==[--gtest_filter=example_test.const_double]==] --gtest_also_run_disabled_tests)
set_tests_properties( example_test.const_double PROPERTIES WORKING_DIRECTORY /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( example_test.const_int /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests/unit_tests [==[--gtest_filter=example_test.const_int]==] --gtest_also_run_disabled_tests)
set_tests_properties( example_test.const_int PROPERTIES WORKING_DIRECTORY /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( exmaple_test.const_bool /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests/unit_tests [==[--gtest_filter=exmaple_test.const_bool]==] --gtest_also_run_disabled_tests)
set_tests_properties( exmaple_test.const_bool PROPERTIES WORKING_DIRECTORY /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( quit_test.test_quit /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests/unit_tests [==[--gtest_filter=quit_test.test_quit]==] --gtest_also_run_disabled_tests)
set_tests_properties( quit_test.test_quit PROPERTIES WORKING_DIRECTORY /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( pause_test.test_pause /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests/unit_tests [==[--gtest_filter=pause_test.test_pause]==] --gtest_also_run_disabled_tests)
set_tests_properties( pause_test.test_pause PROPERTIES WORKING_DIRECTORY /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( audio_test.test_audio /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests/unit_tests [==[--gtest_filter=audio_test.test_audio]==] --gtest_also_run_disabled_tests)
set_tests_properties( audio_test.test_audio PROPERTIES WORKING_DIRECTORY /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
add_test( seek_test.test_seek /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests/unit_tests [==[--gtest_filter=seek_test.test_seek]==] --gtest_also_run_disabled_tests)
set_tests_properties( seek_test.test_seek PROPERTIES WORKING_DIRECTORY /Users/aaronpeng/Desktop/SE/PP/PonyPlayer/debug/src/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==] LABELS unit)
set( unit_tests_TESTS example_test.const_double example_test.const_int exmaple_test.const_bool quit_test.test_quit pause_test.test_pause audio_test.test_audio seek_test.test_seek)
