# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
# {APP_DIR}
# {QT_DIR}
# {VERSION}
version: 1
AppDir:
  path: {APP_DIR}
  app_info:
    id: net
    name: PonyPlayer
    icon: ponyicon
    version: {VERSION}
    exec: usr/bin/PonyPlayer
    exec_args: $@
  apt:
    arch:
      - amd64
    allow_unauthenticated: true
    sources:
      - sourceline: deb {APT_SRC} focal main restricted
      - sourceline: deb {APT_SRC} focal-updates main
          restricted
      - sourceline: deb {APT_SRC} focal universe
      - sourceline: deb {APT_SRC} focal-updates universe
      - sourceline: deb {APT_SRC} focal multiverse
      - sourceline: deb {APT_SRC} focal-updates multiverse
      - sourceline: deb {APT_SRC} focal-backports
          main restricted universe multiverse
      - sourceline: deb {APT_SRC} focal-security
          main restricted
      - sourceline: deb {APT_SRC} focal-security
          universe
      - sourceline: deb {APT_SRC} focal-security
          multiverse
    include:
      - adwaita-icon-theme
      - fonts-dejavu-core
      - libcom-err2:amd64
      - libdbus-1-3:amd64
      - libgpg-error0:amd64
      - libkeyutils1:amd64
      - liblzma5:amd64
      - libpcre3:amd64
      - libsystemd0:amd64
      - libtinfo6:amd64
      - libuuid1:amd64
      - locales
      - tzdata
  runtime:
    env:
      QML2_IMPORT_PAT: '${APPDIR}/{QT_DIR}/qml/'
  files:
    include:
    - {QT_DIR}/lib/libQt6Core.so.6
    - {QT_DIR}/lib/libQt6DBus.so.6
    - {QT_DIR}/lib/libQt6Gui.so.6
    - {QT_DIR}/lib/libQt6Network.so.6
    - {QT_DIR}/lib/libQt6Qml.so.6
    - {QT_DIR}/lib/libQt6Quick.so.6
    - {QT_DIR}/lib/libicudata.so.56
    - {QT_DIR}/lib/libicui18n.so.56
    - {QT_DIR}/lib/libicuuc.so.56
    - {QT_DIR}/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
    - {QT_DIR}/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
    - {QT_DIR}/plugins/platforms/../../lib/libQt6WaylandClient.so.6
    - {QT_DIR}/plugins/platforms/libqeglfs.so
    - {QT_DIR}/plugins/platforms/libqlinuxfb.so
    - {QT_DIR}/plugins/platforms/libqminimal.so
    - {QT_DIR}/plugins/platforms/libqminimalegl.so
    - {QT_DIR}/plugins/platforms/libqoffscreen.so
    - {QT_DIR}/plugins/platforms/libqvkkhrdisplay.so
    - {QT_DIR}/plugins/platforms/libqvnc.so
    - {QT_DIR}/plugins/platforms/libqwayland-egl.so
    - {QT_DIR}/plugins/platforms/libqwayland-generic.so
    - {QT_DIR}/plugins/platforms/libqxcb.so
    - {QT_DIR}/plugins/platformthemes/libqgtk3.so
    - {QT_DIR}/plugins/platformthemes/libqxdgdesktopportal.so
    - {QT_DIR}/plugins/wayland-decoration-client/libbradient.so
    - {QT_DIR}/plugins/wayland-graphics-integration-client/../../lib/libQt6WaylandEglClientHwIntegration.so.6
    - {QT_DIR}/plugins/wayland-graphics-integration-client/libqt-plugin-wayland-egl.so
    - {QT_DIR}/plugins/wayland-graphics-integration-client/libshm-emulation-server.so
    - {QT_DIR}/plugins/wayland-graphics-integration-client/libvulkan-server.so
    - {QT_DIR}/plugins/wayland-shell-integration/libfullscreen-shell-v1.so
    - {QT_DIR}/plugins/wayland-shell-integration/libivi-shell.so
    - {QT_DIR}/plugins/wayland-shell-integration/libwl-shell-plugin.so
    - {QT_DIR}/plugins/wayland-shell-integration/libxdg-shell.so
    - {QT_DIR}/qml/**
    - {QT_DIR}/plugins/sqldrivers/libqsqlite.so
    - {QT_DIR}/plugins/xcbglintegrations/libqxcb-egl-integration.so
    - {QT_DIR}/plugins/xcbglintegrations/libqxcb-glx-integration.so
    # - {QT_DIR}/qml/QtQml/WorkerScript/../../../lib/libQt6QmlWorkerScript.so.6
    # - {QT_DIR}/qml/QtQml/WorkerScript/libworkerscriptplugin.so
    # - {QT_DIR}/qml/QtQml/WorkerScript/qmldir
    - {QT_DIR}/lib/libQt6OpenGL.so.6
    # - {QT_DIR}/qml/QtQuick/../../lib/libQt6QmlModels.so.6
    # - {QT_DIR}/qml/QtQuick/../../lib/libQt6Quick.so.6
    # - {QT_DIR}/qml/QtQuick/libqtquick2plugin.so
    # - {QT_DIR}/qml/QtQuick/qmldir
    - /lib/x86_64-linux-gnu/libEGL_mesa.so.0
    - /lib/x86_64-linux-gnu/libGLX.so.0
    #    - /lib/x86_64-linux-gnu/libGLdispatch.so.0
    #    - /lib/x86_64-linux-gnu/libLLVM-12.so.1
    - /lib/x86_64-linux-gnu/libOpenGL.so.0
    - /lib/x86_64-linux-gnu/libX11.so.6
    #    - /lib/x86_64-linux-gnu/libXau.so.6
    #    - /lib/x86_64-linux-gnu/libXdmcp.so.6
    #    - /lib/x86_64-linux-gnu/libbsd.so.0
    #    - /lib/x86_64-linux-gnu/libedit.so.2
    #    - /lib/x86_64-linux-gnu/libelf.so.1
    #    - /lib/x86_64-linux-gnu/libffi.so.7
    #    - /lib/x86_64-linux-gnu/libfontconfig.so.1
    #    - /lib/x86_64-linux-gnu/libfreetype.so.6
    #    - /lib/x86_64-linux-gnu/libgbm.so.1
    #    - /lib/x86_64-linux-gnu/libgcrypt.so.20
    - /lib/x86_64-linux-gnu/libglapi.so.0
    - /lib/x86_64-linux-gnu/libglib-2.0.so.0
    #    - /lib/x86_64-linux-gnu/libgssapi_krb5.so.2
    #    - /lib/x86_64-linux-gnu/libgthread-2.0.so.0
    #    - /lib/x86_64-linux-gnu/libk5crypto.so.3
    #    - /lib/x86_64-linux-gnu/libkrb5.so.3
    #    - /lib/x86_64-linux-gnu/libkrb5support.so.0
    #    - /lib/x86_64-linux-gnu/liblz4.so.1
    #    - /lib/x86_64-linux-gnu/libpng16.so.16
    #    - /lib/x86_64-linux-gnu/libsensors.so.5
    - /lib/x86_64-linux-gnu/libstdc++.so.6
    #    - /lib/x86_64-linux-gnu/libvulkan.so.1
    #    - /lib/x86_64-linux-gnu/libwayland-client.so.0
    #    - /lib/x86_64-linux-gnu/libwayland-cursor.so.0
    - /lib/x86_64-linux-gnu/libwayland-egl.so.1
    - /lib/x86_64-linux-gnu/libwayland-server.so.0
    - /lib/x86_64-linux-gnu/libxcb-dri2.so.0
    - /lib/x86_64-linux-gnu/libxcb-dri3.so.0
    - /lib/x86_64-linux-gnu/libxcb-present.so.0
    #    - /lib/x86_64-linux-gnu/libxcb-sync.so.1
    #    - /lib/x86_64-linux-gnu/libxkbcommon.so.0
    #    - /lib/x86_64-linux-gnu/libxshmfence.so.1
    #    - /lib/x86_64-linux-gnu/libzstd.so.1
    exclude:
      - usr/share/man
      - usr/share/doc/*/README.*
      - usr/share/doc/*/changelog.*
      - usr/share/doc/*/NEWS.*
      - usr/share/doc/*/TODO.*
  test:
    fedora-30:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
      use_host_x: true
    debian-stable:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
      use_host_x: true
    archlinux-latest:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
      use_host_x: true
    centos-7:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
      use_host_x: true
    ubuntu-xenial:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true
AppImage:
  arch: x86_64
  update-information: guess
